---
- apt:
    name: lxc
    state: present
  become: yes

- name: Setup subuid
  lineinfile:
    line: "{{ lxc_user }}:{{ lxc_subuid_start }}:{{ lxc_subuid_range }}"
    regexp: ^{{ lxc_user }}
    dest: /etc/subuid
    create: yes
  become: yes

- name: Setup subgid
  lineinfile:
    line: "{{ lxc_user }}:{{ lxc_subgid_start }}:{{ lxc_subgid_range }}"
    regexp: ^{{ lxc_user }}
    dest: /etc/subgid
    create: yes
  become: yes

- name: Add lxc-usernet entry
  lineinfile:
    line: "{{ lxc_user }} veth {{ lxc_virbr_name }} {{ lxc_nic_num }}"
    regexp: ^{{lxc_user}}
    dest: /etc/lxc/lxc-usernet
    create: yes
  become: yes

- name: Add $HOME/.config dir
  file:
    dest: "{{ lxc_user_dir }}/.config/lxc"
    state: directory
    recurse: yes

- name: Put user config
  template:
    dest: "{{ lxc_user_dir }}/.config/lxc/default.conf"
    src: default.conf.j2
